version: "3.4"
services:

  openscad-build:
    image: openscad-build:latest
    build:
      context: .
      target: base

  dev:
    image: openscad-build:dev
    build:
      context: .
      target: dev
    volumes:
      - ./src:/src
      - ./tests:/tests
